/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */


/* Triggers (must be defined by user): */

void airspeed_violation(double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double);

/* External variables (must be defined by user): */

extern int64_t clk_nanosec;
extern double airspeed;
extern double max_airspeed;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step();