void takeoff_altitude_violation (double measured0, int64_t clk0,
                                 double measured1, int64_t clk1,
                                 double measured2, int64_t clk2,
                                 double measured3, int64_t clk3,
                                 double measured4, int64_t clk4,
                                 double measured5, int64_t clk5,
                                 double measured6, int64_t clk6,
                                 double measured7, int64_t clk7,
                                 double measured8, int64_t clk8,
                                 double measured9, int64_t clk9,
                                 double measured10, int64_t clk10,
                                 double expected);

void airspeed_violation (double measured0, int64_t clk0,
                         double measured1, int64_t clk1,
                         double measured2, int64_t clk2,
                         double measured3, int64_t clk3,
                         double measured4, int64_t clk4,
                         double measured5, int64_t clk5,
                         double measured6, int64_t clk6,
                         double measured7, int64_t clk7,
                         double measured8, int64_t clk8,
                         double measured9, int64_t clk9,
                         double measured10, int64_t clk10,
                         double max);

void afterburner_violation (bool measured0, int64_t clk0,
                            bool measured1, int64_t clk1,
                            bool measured2, int64_t clk2,
                            bool measured3, int64_t clk3,
                            bool measured4, int64_t clk4,
                            bool measured5, int64_t clk5,
                            bool measured6, int64_t clk6,
                            bool measured7, int64_t clk7,
                            bool measured8, int64_t clk8,
                            bool measured9, int64_t clk9,
                            bool measured10, int64_t clk10);

void stall_warning_pitch_violation (bool measured0, int64_t clk0, float pitch0,
                                    bool measured1, int64_t clk1, float pitch1,
                                    bool measured2, int64_t clk2, float pitch2,
                                    bool measured3, int64_t clk3, float pitch3,
                                    bool measured4, int64_t clk4, float pitch4,
                                    bool measured5, int64_t clk5, float pitch5,
                                    bool measured6, int64_t clk6, float pitch6,
                                    bool measured7, int64_t clk7, float pitch7,
                                    bool measured8, int64_t clk8, float pitch8,
                                    bool measured9, int64_t clk9, float pitch9,
                                    bool measured10, int64_t clk10, float pitch10);
