/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */


/* Triggers (must be defined by user): */

void stall_warning_pitch_violation(bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float, bool, int64_t, float);

/* External variables (must be defined by user): */

extern int64_t clk_nanosec;
extern bool stall_warning;
extern float pitch_deg;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step();