/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */


/* Triggers (must be defined by user): */

void afterburner_violation(bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t, bool, int64_t);

/* External variables (must be defined by user): */

extern bool afterburner_on;
extern int64_t clk_nanosec;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step();