/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */


/* Triggers (must be defined by user): */

void takeoff_altitude_violation(double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double, int64_t, double);

/* External variables (must be defined by user): */

extern int64_t clk_nanosec;
extern bool takeoff;
extern double altitude_ft;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step();